USE [master]
GO

/****** Object:  Database [fabrica]    Script Date: 29/11/2024 17:53:33 ******/
CREATE DATABASE [fabrica]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fabrica', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\fabrica.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fabrica_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\fabrica_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fabrica].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fabrica] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fabrica] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fabrica] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fabrica] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fabrica] SET ARITHABORT OFF 
GO

ALTER DATABASE [fabrica] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fabrica] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fabrica] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fabrica] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fabrica] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fabrica] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fabrica] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fabrica] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fabrica] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fabrica] SET  ENABLE_BROKER 
GO

ALTER DATABASE [fabrica] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fabrica] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fabrica] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fabrica] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fabrica] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fabrica] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fabrica] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fabrica] SET RECOVERY FULL 
GO

ALTER DATABASE [fabrica] SET  MULTI_USER 
GO

ALTER DATABASE [fabrica] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fabrica] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fabrica] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fabrica] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fabrica] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fabrica] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [fabrica] SET QUERY_STORE = OFF
GO

ALTER DATABASE [fabrica] SET  READ_WRITE 
GO

